# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dog-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'
  # Pods for Dog-ios

  target 'Dog-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dog-iosUITests' do
    # Pods for testing
  end

end
